[package]
name = "binconf"
version = "0.1.501"
edition = "2021"
authors = ["OLoKo64 <reinaldorozatoj.11cg1@aleeas.com>"]
description = "Save and load from a binary configuration file with ease."
categories = ["config"]
keywords = ["hash", "config", "binary", "toml", "json"]
repository = "https://github.com/OLoKo64/binconf"
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "examples"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["binary-conf"]
full = ["binary-conf", "toml-conf", "json-conf", "yaml-conf", "ron-conf"]
binary-conf = ["dep:bincode", "dep:md-5"]
toml-conf = ["dep:toml"]
json-conf = ["dep:serde_json"]
yaml-conf = ["dep:serde_yaml"]
ron-conf = ["dep:ron"]

[dependencies]
bincode = { version = "1.3.3", optional = true }
dirs = "5.0.1"
md-5 = { version = "0.10.5", optional = true }
ron = { version = "0.8.0", optional = true }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = { version = "1.0.96", optional = true }
serde_yaml = { version = "0.9.21", optional = true }
toml = { version = "0.7.4", optional = true }
