[package]
name = "binconf"
version = "0.1.3"
edition = "2021"
authors = ["OLoKo64 <reinaldorozatoj.11cg1@aleeas.com>"]
description = "Save and load from a binary configuration file with ease."
categories = ["config"]
keywords = ["hash", "binary", "config", "hasher", "configuration"]
repository = "https://github.com/OLoKo64/binconf"
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["binary"]
binary = ["bincode", "md-5"]
toml = []

[dependencies]
bincode = { version = "1.3.3", optional = true }
dirs = "5.0.1"
md-5 = { version = "0.10.5", optional = true }
serde = { version = "1.0.163", features = ["derive"] }
