[package]
name = "binconf"
version = "0.1.2"
edition = "2021"
authors = ["OLoKo64 <reinaldorozatoj.11cg1@aleeas.com>"]
description = "Save and load from a binary configuration file with ease."
categories = ["config"]
keywords = ["hash", "binary", "config", "hasher", "configuration"]
repository = "https://github.com/OLoKo64/binconf"
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
dirs = "5.0.1"
md-5 = "0.10.5"
serde = { version = "1.0.163", features = ["derive"] }
